// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"time"
)

type Book struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	Author    string    `json:"author"`
	IsRead    bool      `json:"is_read"`
	Year      int64     `json:"year"`
	CreatedAt time.Time `json:"created_at"`
}
